#!/bin/bash

# Nerd Font glyphs (Material Design / Symbols Nerd Font).
# https://www.nerdfonts.com/cheat-sheet
ICON_APPLE=󰀵
ICON_WIFI_ON=󰤨
ICON_WIFI_OFF=󰤮
ICON_WIFI_DISCONNECTED=󰤯
ICON_WIFI_IP=󰩠
ICON_WIFI_SETTINGS=󰒓
ICON_BT_ON=󰂯
ICON_BT_CONNECTED=󰂱
ICON_BT_OFF=󰂲
ICON_SETTINGS=󰒓
ICON_SLEEP=󰒲
ICON_LOCK=󰌾
ICON_REFRESH=󰑐
ICON_INFO=󰋼
ICON_POWER=󰐥
ICON_COPY=󰆏

ICON_VOLUME_100=󰕾
ICON_VOLUME_66=󰖀
ICON_VOLUME_33=󰕿
ICON_VOLUME_10=󰕿
ICON_VOLUME_0=󰝟

ICON_BATTERY_100=󰁹
ICON_BATTERY_75=󰂁
ICON_BATTERY_50=󰁿
ICON_BATTERY_25=󰁻
ICON_BATTERY_0=󰂎
ICON_BATTERY_CHARGING=󰂄
