#!/usr/bin/env zsh
# https://github.com/neutonfoo/dotfiles/tree/main/.config/sketchybar
# Spaces use AeroSpace (not yabai). See plugins/aerospacer.sh.

SKETCHYBAR_CONFIG="$HOME/.config/sketchybar"
export CONFIG_DIR="$SKETCHYBAR_CONFIG"

APP_FONT="$HOME/Library/Fonts/sketchybar-app-font.ttf"
if [ -f "$APP_FONT" ]; then
  sketchybar --load-font "$APP_FONT"
fi

# Notch only on the laptop: if the main display is not Built-in, use desktop rc.
MAIN_DISPLAY=$(system_profiler SPDisplaysDataType | grep -B 3 'Main Display:' | awk '/Display Type/ {print $3}')

if [[ $MAIN_DISPLAY = "Built-in" ]]; then
    source "$SKETCHYBAR_CONFIG/sketchybarrc-laptop"
else
    source "$SKETCHYBAR_CONFIG/sketchybarrc-desktop"
fi
